#include "main.h"

extern "C" {
    #include "ts.h"
}

// needed by scheduler
long int ts_systime() {
    return (long int)HAL_GetTick();
}

void idle(tiny_task_t* task) {
    return;
}

// this is the entry point of the program after STM32 autogenerated initializations are complete
// NOTE: init should not return
void init() {

    // example task
    tiny_task_t idle;
    idle.start_time = 0;
    idle.default_priority = IDLE_PRIORITY;
    ts_add(&idle);

    ts_schedule(NULL, 0);

    while(1) {};
}
